### ISSUE TITLE
Block/Blacklist opening links

### ISSUE THREAD

**Issue by omrikir** [benblack86/linkclump#101]
Please provide the following information when creating a bug report:
I don't understand the "Blacklist" system. I wish to be able to ignore links in selection if it has a specific url
something like if the links is "https://www.google.com/*" and its in the selection it won't be opened.
Is it possible with the current blacklist system?
+ Linkclump version:2.8.3

**Comment by benblack86** [comment]
The blacklist stops the extension from running on certain sites, it doesn't stop links belong to sites from opening.

**Comment by omrikir** [comment]
I see, thanks for the answer.
I don't know where should I say it but I'd like to ask to add this option if its possible.

One more thing, even when a url is in the blacklist the links do open, I wonder why?

**Comment by Hrxn** [comment]
The Blacklist prevents the extension from running, not links from opening.

**Comment by Hrxn** [comment]
Take URL you want to blacklist -> Put that URL into the "Blacklist" form in Linkclump options -> Linkclump will not run if you open that URL in your browser.

**Comment by omrikir** [comment]
I see, thank you.

Would appreciate it if you were to think of adding option to cancel specific url from opening.

Closed

**Comment by benblack86** [comment]
Try the "exclude links with words" option.

**Comment by omrikir** [comment]
"Try the "exclude links with words" option."
I did an it works great, it's just that there are sometimes when you can't exclude all words so I hoped there'd be an option like it.

For example if I'd like to block
www.google.com/gmail
www.google.com/drive?s=1
www.google.com/youtube?wa=false

These examples are not really a working sites but there are sites like this so I hoped I could block all 
"www.google.com/*"
