### ISSUE TITLE
Improper handling of body element margin

### ISSUE THREAD

**Issue by injust** [benblack86/linkclump#103]
Environment: Linkclump `2.8.3` on Chrome `66.0.3359.117` on Windows `10 x64 build 1709`

Given a page with CSS similar to the below:
```html
<html>
<head>
	<style>
		body{
		    margin: 100px;
		    position: relative;
		}
	</style>
</head>

<body>
	<a href>Lorem ipsum dolor sit amet</a>
</body>
</html>
```

Linkclump exhibits unexpected behaviour. The mouse cursor becomes offset from the selection box depending on the values of `margin-top` and `margin-left` for the `body` element.

**Comment by benblack86** [comment]
I suppose we could check to see if this css is set on the body and fix the selection box position appropriately.
