### ISSUE TITLE
Icon for linkclump is greyed out like its not working, but it is

### ISSUE THREAD

**Issue by klepp0906** [benblack86/linkclump#107]
Please provide the following information when creating a bug report:

+ Linkclump version: 2.8.3
+ Operating system: Windows 10 Pro
+ Actions you have setup (screen shoot of options page is fine): deleted the default action and added smartselect - ctrl+left click - urls only and a green box color lol.

the icon was grey upon installing though, has never regained its color so to speak.  restarted browser and pc. 

purely aesthetic best i can tell but google didnt amount to much so figured id post it here :)

**Comment by benblack86** [comment]
I believe it is always greyed out, at least it has always been like that for me.
