### ISSUE TITLE
Not working in Opera

### ISSUE THREAD

**Issue by AthanasiosTs** [benblack86/linkclump#113]
+ Linkclump version: 2.7.3.0 by franmart27
+ Operating system: Mac OS X 10.13.5 64-bit
+Browser: Opera 53.0.2907.110
+ Actions you have setup (screen shoot of options page is fine):
Every time i use Lunkclump in Opera, the links need really long time to open, and my browser crushes.

**Comment by stevenchew83** [comment]
It actually works for opera. but not for www.google.com

**Comment by stevenchew83** [comment]
I apologise. It works. You will have to click on Linkclump "Manage Extension" then enable the following. 
![image](https://user-images.githubusercontent.com/46964317/75617780-bf42ae00-5b9e-11ea-916e-14c24dc3ab36.png)
