### ISSUE TITLE
Dose linkclump support the link with pop-up-confirming page?

### ISSUE THREAD

**Issue by tortoo** [benblack86/linkclump#117]
Just want to know if linkclump support this because those links have one more click to confirm. My test failed and wish to support this.

**Comment by benblack86** [comment]
I'm not sure what you mean

**Comment by tortoo** [comment]
@benblack86 I mean after clicking the link it'll give a popup window which has CANCELl and OK button and should be clicked to continue.

**Comment by benblack86** [comment]
No, that is not supported

**Comment by tortoo** [comment]
Thanks!
