### ISSUE TITLE
Please add an option to open on the current page

### ISSUE THREAD

**Issue by tortoo** [benblack86/linkclump#118]
Because some links can only be opened in the current page as default. If they are opened on new tabs the pages will show `the page doesn't exist`.

Please provide the following information when creating a bug report:

+ Linkclump version: 2.8.5
+ Operating system: Mac OS X 10.11.6
+ Actions you have setup (screen shoot of options page is fine):

**Comment by hao-flexport** [comment]
It seems custom route with an SPA. But still you can not open more than two pages in this case. If only one, why not just by one-click?
