### ISSUE TITLE
It's not smart anymore

### ISSUE THREAD

**Issue by marcopanichi** [benblack86/linkclump#121]
+ Linkclump version: 2.8.5
+ Operating system: win7 - chrome 70.0.3538.67
+ Actions you have setup: see attachment

What I do:
- I select some link from a google serp

What I expect:
- "Translate" link are not selected, because they are not my intention (the extension used to do it before); in other words they are smaller than the link on the title of the snippet

What happens:
- "Translate" link are selected

Thank you,

Marco
![error](https://user-images.githubusercontent.com/4515225/47424053-fcb35200-d786-11e8-8749-ad5558c2ce60.jpg)
![options](https://user-images.githubusercontent.com/4515225/47424054-fd4be880-d786-11e8-8bfd-3859d4ab150b.jpg)

**Comment by hao-flexport** [comment]
To this single case, you can circumvent it easily.
The key point may be to figure out how to meet you requirement.
By providing configurable filters?
