### ISSUE TITLE
Doesn't  work with links in table or webpages generated by excel

### ISSUE THREAD

**Issue by fgykcgcgykk** [benblack86/linkclump#131]
Please provide the following information when creating a bug report:

+ Linkclump version:2.8.6
+ Operating system:Win 10 64b
+ Actions you have setup (screen shoot of options page is fine): no clue what this means

I have a webpage generated by saving an excel file as html, and is impossible to select a rectangle to mark the hyperlinks.

I think that the rectangle tool doesn't work when the links are in a table.

I attach an example file.

[Control.zip](https://github.com/benblack86/linkclump/files/3451922/Control.zip)

**Comment by hao-flexport** [comment]
Maybe a screenshot is preferred for troubleshooting.
