### ISSUE TITLE
Hung, will not release selection window from mouse control  

### ISSUE THREAD

**Issue by Braxton-signaturemillwork** [benblack86/linkclump#134]
Cannot get it to release window from mouse control. Limited to 35 items in a list.  

Please provide the following information when creating a bug report:

+ Linkclump version: latesta as of 11/27/19
+ Operating system: Win 10 Pro - Version 1909 - OS Build 18363.476
+ Actions you have setup (screen shoot of options page is fine):
![image](https://user-images.githubusercontent.com/58271051/69751276-5ddcf000-1114-11ea-8c33-f21242ab7508.png)

**Comment by Braxton-signaturemillwork** [comment]
![image](https://user-images.githubusercontent.com/58271051/69751814-74377b80-1115-11ea-9362-3dbaf1d809fb.png)

**Comment by Braxton-signaturemillwork** [comment]
Have .mov video that gives better description of problem.

**Comment by benblack86** [comment]
Screen shoot of options page would be good

**Comment by Braxton-signaturemillwork** [comment]
[cid:image002.jpg@01D5A529.437F8350]

Best regards,


Braxton Miller l Signature Millwork
O: 972.241.9535 x1011 M: 940.218.0225
2861 Merrell Road l Dallas TX 75229

Certified: WBE/HUB Company
Certified: FSC® COC (FSC-C122441)
