### ISSUE TITLE
Not applying configurations shown

### ISSUE THREAD

**Issue by stdedos** [benblack86/linkclump#138]
Please provide the following information when creating a bug report:

+ Linkclump version: 2.8.8
+ Operating system: Ubuntu / GChrom 79.0.3945.130
+ Actions you have setup (screen shoot of options page is fine):
![image](https://user-images.githubusercontent.com/133706/73457891-090c5e80-437d-11ea-84ff-e905a6cc7e32.png)

Before creating the green entry, I toggled the orange one from open to copy and backwards.

It seems that smartselect "stuck" in there. (probably an annoyance, and it doesn't mean anything)

**Comment by stdedos** [comment]
_Any_ comment on why/how you closed this would be a common courtesy ...

**Comment by stdedos** [comment]
_Any_ comment on why/how you closed this would be a common courtesy ...

**Comment by benblack86** [comment]
As you say "probably an annoyance, and it doesn't mean anything"
