### ISSUE TITLE
Prevent Duplicate Links from Opening when Parameters are Different

### ISSUE THREAD

**Issue by Julian88Tex** [benblack86/linkclump#139]
This is a request for a feature that prevents duplicate links from opening when parameters are different. There are times when I want to open a large number of links on a page. Depending on what's on the page, sometimes there are multiples of the same link. It would be nice to not have these duplicate links open up but only unique links open. I could see this being the default way of opening links and/or a setting.

P.S. Really love this extension! Thanks!

**Comment by benblack86** [comment]
This should already be the case

**Comment by Julian88Tex** [comment]
@benblack86 thanks for mentioning and yes did a test and you are correct if it is the exact same link. I think what is more accurately causing the situation I'm seeing is it doesn't recognize links with the same URL but different parameters as being a duplicate. While I could see this being useful at times (like trying to get to a bunch of different anchor tags) I feel like that's an edge case that could perhaps be a setting if needed and/or a different keyboard shortcut. Most of the time I want it to just dedupe the URL since I might have links all to the same page but with slightly different parameters when in reality I don't want it to open with all those different parameters multiple times.

Example that will open two pages:

https://google.com
https://google.com?test=test
