### ISSUE TITLE
can this work for Google Drive?

### ISSUE THREAD

**Issue by aminco-edw** [benblack86/linkclump#140]
When you're in Google Drive, if you want to open say a bunch of Google Sheets, you have to double-click on each one, end up on a new tab, then go back to the Google Drive window and repeat as many times as needed.

Is there a way to use linkclump on this so you can "bulk open" a bunch of Google Sheets at once? I've tried it and also remapped the key (because "z" in Google Drive means "move file") but can't seem to get it to work.

**Comment by benblack86** [comment]
No, google drive is a very complicated app and this extension is just for opening links.

**Comment by aminco-edw** [comment]
Darn, I didn't think so. Thanks!
