### ISSUE TITLE
Google Images Right Click

### ISSUE THREAD

**Issue by Jesse-Hufstetler** [benblack86/linkclump#141]
When I use Google Images the extension randomly triggers every minute or so when I haven't right-clicked anything. Seems like the upper-left corner of the selection box is always the upper-left corner of the page. Almost seems like a right click event is getting fired in the JS somewhere in Google Images. I suppose that's not the extension's fault but lots of people probably use the action screenshotted below and lots of people use google images 🤷‍♂️. I might dig into fixing it myself if I have time, I actually have [some experience making chrome extensions](https://chrome.google.com/webstore/search/Jesse%20Hufstetler).

+ Linkclump version: 2.8.8
+ Operating system: Windows 10
+ Actions you have setup (screen shoot of options page is fine):
![image](https://user-images.githubusercontent.com/59510530/76978469-1a013700-690d-11ea-84cb-1c09c20a96bf.png)

**Comment by benblack86** [comment]
Sounds like an issue with google images if your theory is correct. The default is to use a key + mouse button to prevent this problem.

**Comment by ZIK999** [comment]
I have settings and same problem.
Using "key + mouse" is not a solution.

**Comment by benblack86** [comment]
@ZIK999 why not?

**Comment by Jesse-Hufstetler** [comment]
@ZIK999 is probably going to say something along the lines of "because it should just work". Thing is, this is free software that is up against a weird edge case and you have to be mindful of that.

Could we maybe have a regex match where if the URL matches a regex we don't run the extension?

**Comment by benblack86** [comment]
@Jesse-Hufstetler haha exactly! There is the blacklist functionality on the options page, I think that should allow regex (https://github.com/benblack86/linkclump/blob/ce7efeddc0cf43fd560f627b5787c0bdcc352ec5/src/linkclump.js#L43)

**Comment by JHufstetlerGH** [comment]
Nice! @ZIK999  I blacklisted by adding the following line to the "Blacklist" text box:
```regex
google\.com/search\?.+tbm=isch
```
I'm happy with this solution, closing the issue

**Comment by JHufstetlerGH** [comment]
oh hey, looks like I can't close the issue. @benblack86 feel free to close it

**Comment by ZIK999** [comment]
Didn't mean to be mean. I use my PC with TV and using "key + mouse" on couch is not reasonable.

Thanks for solution with Blacklist. It worked.
