### ISSUE TITLE
Nolonger working 

### ISSUE THREAD

**Issue by markm3977** [benblack86/linkclump#144]
Please provide the following information when creating a bug report:

+ Linkclump version: 2.8.8
+ Operating system: Windows 10
+ Actions you have setup (screen shoot of options page is fine):
I have removed and re installed, and just does not want to start working again. 

I have chome ver - Version 83.0.4103.61 (Official Build) (64-bit)

**Comment by anthonyrsc** [comment]
Same as above. 
It seems since Chrome update to Version 83.0.4103.61 (Official Build) (64-bit)
Keep up the good work :)

**Comment by benblack86** [comment]
It is working for me and I'm on that version of chrome. What exactly isn't working? What OS version?

**Comment by anthonyrsc** [comment]
No highlight shape appears when use the trigger key and left click + drag.
I'm on Windows 10.0.18363 Build 18363

**Comment by benblack86** [comment]
It might be an issue with windows. Unfortunately, I don't have windows so I can't test myself.

**Comment by markm3977** [comment]
I go to select the links and it does not work. 

I have it set to my Right mouse,  I click and hold and goto select, but it does not do it... 

I goto the Test window on the settings tab of the app, but it works... its really strange
