### ISSUE TITLE
LinkClump No Longer Working for Google Drive Shareable Links

### ISSUE THREAD

**Issue by acarterbrightpower** [benblack86/linkclump#147]
Hello, 

Previously, I was using LinkClump to download shareable links from several PDF files in Google Drive. Up until Friday June 19, 2020, using the add-on this way worked. Since then it has not worked. I use L-click + shift and I see the capture box and the number of links captured but it's "0." I am not sure if this is a change with Google Drive, with LinkClump or on my end. Can you please confirm that there were no changes made to the LinkClump code to cause this?

P.S. I tried removing and re-adding the extension and reviewed all my settings. 

Thank you. 

Version: 2.8.9
Operating system: OS Build - 17763.1282, 64-bit, x64 based processor, Windows 10 Pro, Version 1809
Chrome Version: Version 83.0.4103.97 (Official Build) (64-bit)
Actions setup: L-click + shift, open as new tabs, smart select 'on," no exclusions

![image](https://user-images.githubusercontent.com/40034148/85628206-bb4f0600-b63d-11ea-8708-8aa06466eedb.png)

Thank you,

**Comment by benblack86** [comment]
It is a change with google drive. Those files are not rendered as links.

**Comment by acarterbrightpower** [comment]
@benblack86 Thank you for the response. So to clarify (and then I will close this ticket) Google drive may have changed something so that files are no longer recognized as links by third party apps even though they may have been before?

**Comment by benblack86** [comment]
Correct

**Comment by acarterbrightpower** [comment]
Okay. Thank you for your help. Closing this ticket.
