### ISSUE TITLE
Can have a custom CSS

### ISSUE THREAD

**Issue by dnknn** [benblack86/linkclump#148]
Can have a custom CSS of options, with it can easy to change font-size etc.

![0628085523](https://user-images.githubusercontent.com/10995302/85935012-07d86100-b91e-11ea-9182-5478928deda0.png)

**Comment by benblack86** [comment]
I don't understand. Why do you need custom CSS?

**Comment by dnknn** [comment]
@benblack86 
> I don't understand. Why do you need custom CSS?

Because it can customize the 🔢digital indicator, is too small by default.

![0630103853](https://user-images.githubusercontent.com/10995302/86077109-fc23a080-babd-11ea-9531-b433f43e40a1.png)

![CSS](https://user-images.githubusercontent.com/10995302/86077291-4ad13a80-babe-11ea-820c-9a84fe6f2079.gif)

**Comment by benblack86** [comment]
What percentage of users do you think would use this functionality? I'm happy to make the number a little bigger/bolder if you want to submit a PR.

**Comment by dnknn** [comment]
I don't know how to use github-PR, because I don't understand anything except CSS, 
because CSS does not require much logic, so it is relatively simple. 🤦🙈

**Comment by benblack86** [comment]
Never a bad time to start learning

**Comment by dnknn** [comment]
Not a developer, so no need to learn more, 
Thank you very much for your reply, good luck ❣

**Comment by dnknn** [comment]
@benblack86 
Have considered adding a desktop-notification with `Copied to clipboard`

> 🔔Chrome•desktop-notification🔔📜
https://developer.chrome.com/extensions/notifications

**Comment by benblack86** [comment]
Why would that be useful?

**Comment by dnknn** [comment]
Just by the way, it's not very important.
