### ISSUE TITLE
Linkclump's helper, please refer to it.

### ISSUE THREAD

**Issue by dnknn** [benblack86/linkclump#149]
Linkclump can not working in the `iframe` , and no Chrome•desktop-Notifications.
I think it is currently a powerful assistant 🎁 for Linkclump, found it in the Chrome extension store.

**Copy Selected Links** 👇&emsp;&emsp;(When any text is selected, context menu will appear. if contains  URLs, will be copied.)

https://chrome.google.com/webstore/detail/kddpiojgkjnpmgiegglncafdpnigcbij

It has two characteristics:
- #### It can working in the `iframe`
- #### It can ⚙show [Chrome•desktop-Notifications](https://developer.chrome.com/extensions/notifications)

![0713015313](https://user-images.githubusercontent.com/10995302/87253179-ac74aa00-c4ab-11ea-9b2c-e3506d08fbb6.png)

🎀 So I think it is currently a powerful assistant 🎁 for Linkclump.

**Comment by benblack86** [comment]
This is not an issue, therefore, closing.
