### ISSUE TITLE
To avoid the rate-limit!

### ISSUE THREAD

**Issue by prefix309** [benblack86/linkclump#153]
I often have to deal with multiple URLs, and Linkclump does it very well.
But some sites do implement the _rate-limit_ thus making it difficult to work with since LinkClump opens it all at once.
(i.e. [**Pastebin**](https://pastebin.com))

> 429 Too Many Requests
> nginx

My suggestion is to add an option to Blacklist sites that would be loaded sequentially instead of parallelly.

**Comment by benblack86** [comment]
There is an option to delay opening. That would solve your problem without adding more functionality.

**Comment by Lucienest** [comment]
> There is an option to delay opening. That would solve your problem without adding more functionality.

You can add this functionality there @benblack86 
For instance:

- Delay opening on the listed sites.
- Number of seconds to wait
