### ISSUE TITLE
Google Maps right click isn't working

### ISSUE THREAD

**Issue by conracer** [benblack86/linkclump#154]
+ Linkclump version: 2.9.1
+ Operating system: Windows 10 Pro
+ Actions you have setup (screen shoot of options page is fine): I have set up only one action without a "key".

So here is the thing:
If I have your Chrome Addon activated the individual context menu on Google maps (right click on the map) isn't showing up. Now this seems to be a special case regarding the Google maps website because, for example, on the web-version of Spotify (https://open.spotify.com) this individually programmed context menu (on behalf of  Spotify) IS showing up.
Be aware, that you have to use the "non-Lite"-Version of Google Maps because in the "Lite mode" (http://maps.google.com/?force=canvas) this context menu isn't available anyways. So use the standard WebGL-mode (https://www.google.com/maps?force=webgl) where you can view houses in 3D (only big cities) if you hold down the Control-key and drag your mouse at the same time.
Here are my settings:

<img width="468" src="https://user-images.githubusercontent.com/69402933/89720785-4f9adf80-d9d6-11ea-98e0-1ebdce776ffa.png">

**Comment by benblack86** [comment]
The warning message in the screenshot hopefully explains the problem.

**Comment by conracer** [comment]
Sorry, I thougth this was only an issue regarding Linux/Mac, referring to your inapp-FAQ:

<img width="461" src="https://user-images.githubusercontent.com/69402933/89721972-b672c580-d9e3-11ea-9c0f-a0ba401320e9.png">

**Comment by benblack86** [comment]
On windows you have a choice, but it is not recommended.

**Comment by conracer** [comment]
Nice would be to introduce a function where you can blacklist sites where Linkclump interferes with the specific site. One has then to add Linkclump to the Chromemenu and you as the developer have to add a menu entry if the user clicks on the Linkclump-icon.

**Comment by benblack86** [comment]
There is a block list you can add sites to

**Comment by conracer** [comment]
Do you mean this topic?
[https://superuser.com/questions/1546186/enable-disable-chrome-extensions-per-site-via-white-or-blacklist](url)

**Comment by benblack86** [comment]
No, in the options page of linkclump

**Comment by conracer** [comment]
Excuse me. I have overseen that.
