### ISSUE TITLE
make tabs opened by linkclump as child tab of current tab

### ISSUE THREAD

**Issue by hien4990** [benblack86/linkclump#156]
Please provide the following information when creating a bug report:

+ Linkclump version: newest version
+ Operating system: windows 10 1909
+ Actions you have setup (screen shoot of options page is fine):
Please make tabs opened by linkclump as child tab of current tab, not as the same hierarchy of current tab so i can use it easily with sidewise or vivaldi tree tabs. Thanks

**Comment by benblack86** [comment]
Does that functionality exist in chrome?

**Comment by hien4990** [comment]
thanks for answered , i mean that when you "add to new group" a tab, when you open a link in this tab, it's recognized as a child tab of this tab and remain in the group, but when i open with linkclump, it doesnt, so the tabs jump outside the group. I suggest that when i open links with linkclump the tabs stay in the group as a child tabs or the tab group.
