### ISSUE TITLE
Feature request: copy links instead of opening

### ISSUE THREAD

**Issue by dkew8** [benblack86/linkclump#168]
It would've been nice to have this feature — one hotkey for the new tabs and another to copy the links to the clipboard. There is the "copy selected links" extension, but it doesn't pair really well with something like Stylebot. Linkclump works really well, on the other hand.

**Comment by AdamJacobson** [comment]
@dkew8 this already exists. On the options page you can click "Add Action" and create a separate hotkey. Set the action as "Copied to clipboard"
