### ISSUE TITLE
Please support for safari

### ISSUE THREAD

**Issue by lonelygoneby** [benblack86/linkclump#180]
need it,and can sell it on safari app store,not for free.

**Comment by KleinDesigns** [comment]
> need it,and can sell it on safari app store,not for free.

I need it too, would also pay for it in safari App Store (like Tampermonkey).

**Comment by StevenTsao88** [comment]
I'll buy it too

**Comment by mefengl** [comment]
Hey, I reimplemented it in userscript, so that it can be used in Safari by Tampermonkey extension.

https://greasyfork.org/scripts/471560

**Comment by lonelygoneby** [comment]
实在太感谢了，大哥你真的是太厉害了。

**Comment by lonelygoneby** [comment]
实在太感谢了，大哥你真的是太厉害了。

**Comment by KleinDesigns** [comment]
> 

Awesome. Thank you! I will test it timely
