### ISSUE TITLE
Shorcut CTRL + LEFT does not work on mac on Firefox (no other extensions)

### ISSUE THREAD

**Issue by davidtcp** [benblack86/linkclump#198]
I have a problem, shorcut CTRL + LEFT does not work on mac on Firefox. All extensions disabled. it works on Chrome

And if I use SHIFT instead I lose functions.

**Comment by t0mm1e** [comment]
For me it doesn't work in Chrome nor Firefox on MacOS at all.

Tried every combination.

Not sure when this started. I have been an avid user  in the past. I do miss it.

**Comment by davidtcp** [comment]
[t0mm1e] but do you deactivate every chrome extension first?. I have a macbook. If in my macbook works on chrome the chrome extension works ... the only option must be that another chrome extension or APP program get the same short cut key. I end using MOUSE LEFT + a, and MOUSE LEFT + b in booth browser. 

Remember to create the key combination first, change the colour to one you like, SAVE THEM! press and hold the key, in my case "a", and then with the right mouse button /trackpad select an area.

**Comment by t0mm1e** [comment]
I've tried it in Firefox on MacOS, with onlink 1Password and Linkclump installed.
I cannot find any combination that works.

**Comment by t0mm1e** [comment]
Here's one that looks nice and works like a breeze in Firefox:

https://cpriest.github.io/SnapLinksPlus/

For other people looking for something that works. Not available for Chrome anymore it seems.

**Comment by davidtcp** [comment]
Disappeared in chrome and reported in Firefox for injecting code. Thanks, but too much risk. The votes it has distributed among each level are excessively negative.

**Comment by t0mm1e** [comment]
Could be.
Though it is a recommended extension (recommended by Firefox presumably), and the so called code injected seems to be a few HTML tags needed for some procedure. Maybe not desirable, wanted,  or needed, not sure whether that's malicious.

My adblocker removes a gazillion HTML tags and code, code by the website I'm visiting. We're not calling those malicious. Well, marketeers probably do 😊
