### ISSUE TITLE
Box selection does not scroll

### ISSUE THREAD

**Issue by zamarax** [benblack86/linkclump#200]
When drawing the box if there are more links on the visible page the page will scroll but the box does not keep the links it previously held in focus. Would be great if we could get that feature.

I believe it should be possible as most screenshot tools have that built in for scrolling pages.

**Comment by zamarax** [comment]
Any update on this issue?

**Comment by benblack86** [comment]
You need to provide video because I don't know what you mean

**Comment by zamarax** [comment]
https://user-images.githubusercontent.com/25627568/211597142-e07a936a-0873-47fc-ad84-b5e71d33e46f.mp4

Attached is an example

**Comment by benblack86** [comment]
That is more an issue with gmail. If you try it on google search you will see it working.

**Comment by zamarax** [comment]
Not entirely true, the issue presents itself on any page really that has iFrames (I just used gmail.com as an example), by comparison and while they don't do this feature there are other extensions that can scroll an iFrame correctly, such as AwesomeScreenShot.

**Comment by benblack86** [comment]
ok well I'm open to solutions. 

FYI: Please note that support can not be provided as this is a free extension. Developers are welcome to submit PRs at https://github.com/benblack86/linkclump.
