### ISSUE TITLE
sometimes doesn't work

### ISSUE THREAD

**Issue by yjiawqgj** [benblack86/linkclump#204]
Please provide the following information when creating a bug report:

+ Linkclump version:2.9.1
+ Operating system:windows chrome
+ Actions you have setup (screen shoot of options page is fine):
![image](https://user-images.githubusercontent.com/71002956/197341277-2980640c-f1b5-4747-b9b7-7fa84a1805f5.png)

Sometimes there is no response when selecting a link to open, and sometimes it takes several operations to open links in batches.

**Comment by AnthonyBronislavaGonzales** [comment]
Same, can't figure out what makes it fail.
