### ISSUE TITLE
auto-switching tab

### ISSUE THREAD

**Issue by clumpme** [benblack86/linkclump#205]
Chrome Version 107.0.5304.63 (Official Build) (64-bit)
linkclump 2.9.1

Chrome just updated today and now when I open multiple link or single link, chrome auto-switch tab. How do i disable this? I want to stay on the tab that contains the link i'm trying to open as a new tab and not auto-switch to newly opened tabs.

**Comment by fede777** [comment]
Yes, I was going crazy thinking it was some kind of setting or update of the extension. Hope it gets fixed.

**Comment by benblack86** [comment]
Chrome must have changed a behavior. Open to accepting a PR to fix the issue.

**Comment by fede777** [comment]
I'm not familiar with any of this, I assume PR is pull request? Do we have to do something for you to fix it?

**Comment by benblack86** [comment]
I don't have time at the moment.

**Comment by ylxb2016** [comment]
> Yes, I was going crazy thinking it was some kind of setting or update of the extension. Hope it gets fixed.

Going crazy too. 😢 

Is there any other methods to resolve it?

**Comment by hengstchon** [comment]
> Chrome must have changed a behavior. Open to accepting a PR to fix the issue.

Hi benblack86, I have opened a PR https://github.com/benblack86/linkclump/pull/206 to fix this issue. Please check it out.

**Comment by fede777** [comment]
It's live, and working well, thanks

**Comment by clumpme** [comment]
sweet, thanks everything back to normal
