### ISSUE TITLE
update chrome to 107.0.5304.88, multiple tabs open can't stay at current tab

### ISSUE THREAD

**Issue by zcfshadowwork** [benblack86/linkclump#207]
Please provide the following information when creating a bug report:

+ Linkclump version: 2.9.1
+ Operating system: Windows7 64bit,  Chrome 107.0.5304.88
+ Actions you have setup (screen shoot of options page is fine): Thank you for your fabulous extension, I love it very much!  In previous Chrome versions,  I can stay at current tab when I try to open multiple urls with  "Opened as New Tabs" choice,  Then I upgraded my Chrome version to 107.0.5304.88,  it'll just open tabs at the end (I didn't choose "open tabs at the end" ) , could you help me!  I just want to stay at the current tab. Thank you very much!

**Comment by Hrxn** [comment]
use Linkclump v2.9.2

**Comment by zcfshadowwork** [comment]
Thank you! It works perfectly!
