### ISSUE TITLE
Can this extension be made to work on URL scheme "file://" local file system files.

### ISSUE THREAD

**Issue by rluiten** [benblack86/linkclump#208]
I have local file system html files that link to other files as an index system.
It would be very useful for this work on scheme "file:" for me.
Is this possible?
If its possible is it likely it might be done?

+ Linkclump version: 2.9.2
+ Operating system: Windows 10 21H2
+ Actions you have setup (screen shoot of options page is fine):
Default configuration
![image](https://user-images.githubusercontent.com/670472/205220334-c25298e0-bbe9-4c32-b9ce-a345e3ac8a07.png)

**Comment by benblack86** [comment]
<img width="1002" alt="Screen Shot 2022-12-02 at 08 14 41" src="https://user-images.githubusercontent.com/315836/205301043-0a5e56ff-0c67-43ec-8012-29e129c84d5f.png">

**Comment by rluiten** [comment]
I did look through the options, but it appears I am at least partially blind.
Thank you....
