### ISSUE TITLE
New version without updating here what changed, but some useful thing went away

### ISSUE THREAD

**Issue by pacopepepipo** [benblack86/linkclump#212]
Please provide the following information when creating a bug report:

+ Linkclump version: latest
+ Operating system: windows 10 x64
+ Actions you have setup (screen shoot of options page is fine):

Previous to the update: You clicked on 20 links, closed the tab or moved it to a new window, and the links keep opening

AFter the update: you click on 20 links, close the tab with the links, and those links stop opening 

Now you need to maintain the original page of links opened until the last one of them is on a new tab or the extension stops working as intented

**Comment by benblack86** [comment]
This is when you have the timer setup?

**Comment by pacopepepipo** [comment]
yes, I have a delay of 1 second

**Comment by benblack86** [comment]
Should be fixed in 2.9.4 - let me know if it is fixed.

**Comment by pacopepepipo** [comment]
fixed, thanks a lot ben
