### ISSUE TITLE
LinkClump is not working

### ISSUE THREAD

**Issue by Scanto285** [benblack86/linkclump#230]
I have used LinkClump for years with my work and always had great results.  Lately though, (in the last few weeks?) linkclump has stopped functioning.  It APPEARS to be working correctly, I am able to push Z and see the red lasso that grabs and counts the links to be opened, but when I release, nothing happens and the links do not open.

I have tried over and over and over again

I have tried refreshing the page. I have tried shutting down and restarting.  I have tried closing the page and re-opening it....

Every once in a while it will randomly work as expected but the very next time I attempt I get the same blank result.  Is there anything that can be done?  I miss it!

**Comment by CSimonton** [comment]
I have a similar issue.  It opens the tabs, but does not load the website :(
