### ISSUE TITLE
Plans to Update for Manifest V3?

### ISSUE THREAD

**Issue by ZatchHo** [benblack86/linkclump#239]
I fully understand support it not provided for Linkclump, and that as a free tool, it may not be worthwhile for you to update it to be compliant with Manifest V3 (I’m a simpleton - I wouldn’t know if that would require a full rewrite or what). I just wanted to say I would be eternally grateful to be able to continue to use it, as no other extension matches its exceptional capabilities. I also wanted to thank you for the extension, as I’ve been using it for ~ the past eight years and its allowed me to solve problems and accomplish things I might not have otherwise been able to (at least not in a reasonable timeline).

**Comment by benblack86** [comment]
It's probably unlikely I will do it. If someone else does it, I can get the change deployed.

**Comment by ZatchHo** [comment]
Thanks for the reply :)
