### ISSUE TITLE
Interference with vimium

### ISSUE THREAD

**Issue by brokedarius** [benblack86/linkclump#240]
Hi folks so this may not be an issue per say but I think this might be relevant to other users and I was wondering if there was a possible fix for this.

It seems that you can't have linkclump and vimium enabled, if you enable both, linkclump stops working completely. Probably related to how vimium uses the keyboard and takes priority.

Do you think there would be a way to have both co-exist or maybe I should ask this in vimium repo?

Thanks again.

**Comment by McPhale** [comment]
I use vimium and don't have any issues using linkclump; I have the binding set to alt + left mouse drag.
