### ISSUE TITLE
Upgrade to manifest V3

### ISSUE THREAD

**Issue by RealRedcodi** [benblack86/linkclump#245]
The extension will be removed for everyone if it isn't upgraded to manifest V3 soon

**Comment by benblack86** [comment]
Linkclump will not be updated to V3. It will be deprecated instead.

**Comment by fede777** [comment]
For anyone looking for an alternative, there's 2 forks of this extension that are MV3 compatible.

https://chromewebstore.google.com/detail/linkclump-pro/hfollkhbdmgdnakpgocoldgdjaoahhni
https://chromewebstore.google.com/detail/linkclump-plus/ainlglbojoodfdbndbfofojhmjbmelmm
