### ISSUE TITLE
Extension not accepted by Chrome Web Store

### ISSUE THREAD

**Issue by voltzinho** [benblack86/linkclump#248]
Please note that support can not be provided as this is a free extension. Developers are welcome to submit pull requests.
I noticed last day that Chrome has desactivated this fantastic extension because the account is not declared as a prof account in chrome web store. 
Can you share us your plan abot this? The other extension Linkclump Pro is still validated but has some issues...
Can your user community (300'000) not help ?
Thks for your feedback.
Voltzinho

**Comment by pokonski** [comment]
There will be a fork hopefully https://github.com/benblack86/linkclump/pull/243

**Comment by fede777** [comment]
For anyone looking for an alternative, there's 2 forks of this extension that are MV3 compatible.

https://chromewebstore.google.com/detail/linkclump-pro/hfollkhbdmgdnakpgocoldgdjaoahhni
https://chromewebstore.google.com/detail/linkclump-plus/ainlglbojoodfdbndbfofojhmjbmelmm

**Comment by voltzinho** [comment]
Tels

David Voltz
Route des Esserts, 3
CH-1031 Mex
