### ISSUE TITLE
Feature Request: Send directly to download

### ISSUE THREAD

**Issue by mattyb** [benblack86/linkclump#28]
It would be great to be able to send a bunch of links directly to the download manager without passing through tabs. For example, downloading 500+ files from the [DC City Data Repository](http://data.dc.gov/NewCalendar.aspx?where=Citywide&area=&what=CSV&date=lastmodifieddate&from=5%2f11%2f2010+12%3a00%3a00+AM&to=6%2f11%2f2013+11%3a59%3a00+PM&dataset=OTR_PROPERTY&datasetid=10&whereInd=0&areaInd=0&whatInd=0&dateInd=0&whenInd=4&disposition=attachment&showextra=1)

![image](https://f.cloud.github.com/assets/52160/640567/bcd14728-d2ff-11e2-8274-b06952cc80ea.png)

**Comment by thibaultmol** [comment]
How does the workaround work?
