### ISSUE TITLE
Opera support?

### ISSUE THREAD

**Issue by ghost** [benblack86/linkclump#37]
Hello,

Can you make the Opera support (Chromium-based)?
Thanks for answer.

Regards!

**Comment by telephone** [comment]
Just a friendly bump in case others face the same issue.

For Opera 15+ (Chromium based), you can use [Download Chrome Extension](https://addons.opera.com/en/extensions/details/download-chrome-extension-9/?display=en) to install extensions from the Chrome Web Store. Thus, allowing you to bypass the limited extensions within the Opera Add-ons.
