### ISSUE TITLE
Linux support?

### ISSUE THREAD

**Issue by Oxicode** [benblack86/linkclump#39]

**Comment by spoid** [comment]
For people landing here like I just did - Your problem might have been that for some reason, you can not assign just the right mouse button to linkclump which is the standard under Windows. You need to set up a different combination in the settings, like middle mouse button or [Modifier]+Right Click.

I sure would love to have the right click though. :D

**Comment by benblack86** [comment]
Linux chrome handles click mouse events differently than windows chrome and therefore its not possible to provide the same behavior.
