### ISSUE TITLE
Linkclump stopped working on specific web pages

### ISSUE THREAD

**Issue by NancyGE** [benblack86/linkclump#40]
System: Windows XP Pro SP3 (fully updated)
Chrome Version 37.0.2062.124 m
Antivirus: Panda Cloud

I've been using Linkclump for months now and been well pleased. But in the last week or 10 days, behavior has changed dramatically. When I test functionality on the Guide page it works as expected. But on several pages I use daily (examples below) the first 2 pages from my selection open according to the settings (20 seconds open; 30 seconds close) except the tabs never close and no further links open.  I've tried the following:
1.  suspending AV
2. updating Chrome
3. uninstall/reinstall Linkclump
4, testing various Options settings (15/20; 30/45; 30/59) etc.
5. limiting link selection to 10 links at a time (50 was my usual selection).
I can't think of anything further to try, hence this post.  Thank you in advance for your assistance.

Examples:
http://happyfunbwsblog.blogspot.com.au/
(newest coins tab)
http://bubblewitchsagaallhelpandactivities.blogspot.com/search/label/COINS%20-%20Sept%2027

**Comment by benblack86** [comment]
Closing due to no response.
