### ISSUE TITLE
Link Clump not working

### ISSUE THREAD

**Issue by pokie76** [benblack86/linkclump#41]
I've been using Linkclump for months and now I and others have tried to use it and its not working...

i have highlighted links on my game site and in google to test. and then i right click and link clump is not there to click on to open selected links...

i have tried it on windows 8 and well as vista and all my friends are running windows 8 as well and some are running link clump app

Please take a look at this asap

**Comment by pokie76** [comment]
yes, people take streetwars to be a very serious game sometimes and its stupid... 

my user name is pokie76 --- go see my pro. i am over 450 million stats

i uses firefox and i think i got it to work somewhat 

Date: Tue, 30 Dec 2014 16:39:15 -0800

**Comment by benblack86** [comment]
Closing as this is an old ticket.
