### ISSUE TITLE
Linux issue. Right click opening menu and not the yellow box

### ISSUE THREAD

**Issue by modzmarvin** [benblack86/linkclump#42]
I run this on linux and when I right click to start selecting the links, it instantly opens up the menu (right click menu) and I cant get it to start showing the yellow box. 
Any fixes to this?

Works perfect for windows and claims support for linux.

**Comment by benblack86** [comment]
Mouse+Key combination are different on the different operating systems. Please follow instructions provided by the guide.

**Comment by modzmarvin** [comment]
Thanks, dude, press shift.

P.s I recommend making the guide simpler to find.
