### ISSUE TITLE
Chrome Extension Not Working

### ISSUE THREAD

**Issue by mrscopophilia** [benblack86/linkclump#43]
I am a long time user of LinkClump and over the last few months it has been intermittently not working.  I have been able to simply restart Chrome and it would work again.  Now today I cannot get it to work at all.  I have restarted Chrome, disabled and re-enabled the extension, removed and reinstalled the extension, and restarted the computer.  No luck it getting it to work.

This is happening on all websites.

Windows 8.1 Pro with all updates installed
Chrome version 43.0.2357.65 m
LinkClump v2.7.3

**Comment by benblack86** [comment]
Do you get any errors? What settings do you have on the linkclump options page? Do you have other extensions installed that could be interfering with it?
