### ISSUE TITLE
Linkclump blocks right click menu on PDF files opened in Chrome

### ISSUE THREAD

**Issue by WVergeer** [benblack86/linkclump#45]
(I've also posted this issue in the Chrome web store)

If I have Linkclump enabled as Chrome extension, the right-click menu doesn't appear when I (right) click a PDF file that is opened in the browser. 

If I disable the Linkclump extension, restart Chrome, the right menu appears. If I enable Linkclump again, restart Chrome, the right menu doesn't work anymore.

You can test this by right-clicking https://partners.adobe.com/public/developer/en/xml/AdobeXMLFormsSamples.pdf. 

My UA string is: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.80 Safari/537.36

If desired, I can provide a screencast video showing this issue.

**Comment by WVergeer** [comment]
I'm using  Linkclump 2.7.3

**Comment by benblack86** [comment]
I can reproduce, but I don't have time to investigate further. I would guess it is a problem on the chrome side since the extension doesn't do anything special for pdfs.

**Comment by WVergeer** [comment]
OK, the Chromium team closed my ticket after they heard it was a Linkclump
specific issue. So, if you do have time, I would recommend to use the
Chromium boards and report that you think it is a Chrome issue.

See: https://code.google.com/p/chromium/issues/detail?id=546673

For me, either is fine. I can just enable Linkclumb whenever I need it and
keep it disabled if not. So, do with it as you please.

And thanks btw for this great extension. Much appreciated!

Best,

Wouter

**Comment by erlendorf** [comment]
[This line of code](https://github.com/benblack86/linkclump/blob/0e7331a89ba9f3aa51a55933e954a4ba9fc072fb/src/linkclump.js#L202) is the culprit.

**Comment by benblack86** [comment]
That line of code doesn't get hit unless linkclump is activated (i.e. you are drawing the box). I've just tried again and right click is now working on a pdf file.

**Comment by erlendorf** [comment]
I only get the bug when I have set an action with right-mouse-button + no key as a trigger.

I also found that actions with right-mouse-button don't work at all for me (not even a border is drawn when I try to select links), regardless if there's a key set or not.

**Comment by benblack86** [comment]
Were you using a mac? Short story is you can't only use right mouse button. There was a bug on the options page that allowed that and has now been fixed. Please select a key if you want to use right mouse button.

**Comment by erlendorf** [comment]
I'm using Windows, and this problem is still occuring -- just tried on a clean profile. Only after I installed linkclump, does the context menu on PDFs no longer open. I'm working on a fix

**Comment by erlendorf** [comment]
Seems like when I right-click, the mouse is moved a tiny, non-noticable bit (I have a high DPI screen)

**Comment by erlendorf** [comment]
I haven't changed any settings, so this can't be the culprit

**Comment by erlendorf** [comment]
The mouseup() function gets triggered every time I right click on a PDF

**Comment by benblack86** [comment]
On a normal web page, mac and windows behavior differently with right mouse button. On mac, the menu pops up on mouse button down. On windows, the menu pops up on mouse button up. Therefore, to not interrupt the menu I disallow only using the right mouse button on mac.

I don't have access to a windows computer any more so I can't test myself, but maybe on a pdf the menu pops up on mouse button down. If that is the case, then maybe I should also disallow only using right mouse button on windows too. If you use a key with the right mouse button, it should work. Can you try that?

**Comment by erlendorf** [comment]
Adding a key in the Linkclump settings indeed fixes the issue. As the issue is only occuring on PDF pages, the best thing to do IMO would be for Linkclump to detect if it's on a PDF page.

**Comment by thecakeisalie25** [comment]
Could this be due to the way that chrome(ium) views PDFs inside some viewer instead of just as a scrollable page?

**Comment by benblack86** [comment]
Duplicates #63
