### ISSUE TITLE
Currently, the first selected URL ends up on the far right of my tabs #UXD #Bug

### ISSUE THREAD

**Issue by ldexterldesign** [benblack86/linkclump#47]
Hey,

Thanks for a wonderfully useful extension

🙏 As a desktop (Apple MBP, El Capitan, Chrome v47) user, when I open a list of URLs, I want the URLs to open in the order I selected; from left-to-right in tabs. Currently, the first selected URL ends up on the far right of my tabs #UXD #Bug - if you agree reply +1 or vote this up

Will update my rating if this is fixed and/or I receive a response from the creator here or via email chrome.google@ldexterldesign.co.uk

Hope this is useful

Regards

<img width="1440" alt="screen shot 2015-12-16 at 07 34 16" src="https://cloud.githubusercontent.com/assets/1715809/11834137/bf848d70-a3c9-11e5-9a74-e374fae94fb4.png">

**Comment by benblack86** [comment]
You can reverse the ordering by selecting that option from the settings page.

![screen shot 2015-12-16 at 09 56 29](https://cloud.githubusercontent.com/assets/315836/11844197/792715de-a3db-11e5-9cdc-7db793a1010a.png)

**Comment by ldexterldesign** [comment]
Hey,

Apologies for delay - bit behind on email ATM

Thanks for reply

Yes, I am aware of that feature, although reversing the order of the tabs isn't my goal. Achieving any sort of order at all was/is my issue.

I had another look at this today, since it's something I'm still sporadically suffering from...

I have another two conflicting Chrome extensions, resolving this issue fixes your extension, so I don't think it's your problem

Apolgies
