### ISSUE TITLE
Enable it to work on any page open in a tab?

### ISSUE THREAD

**Issue by h259bws** [benblack86/linkclump#49]
I was hoping that this would replace the now-obsolete Firefox extension called TXTlinkTAB (http://www.txtlinktab.com/), which would allow even a text file open in a browser to have its links (written as plain text with an Anchor tag) highlighted and then opened in a new tab. Is that possible with Linkclump, or is it on your product roadmap?

Thanks!

**Comment by benblack86** [comment]
Checkout out the FAQ on the options page chrome-extension://lfpjkncokllnfokkgpkobnkbkmelfefj/pages/options.html

**Comment by benblack86** [comment]
Closing due to no response
