### ISSUE TITLE
Interferes with Google Photos Functionality

### ISSUE THREAD

**Issue by bzle** [benblack86/linkclump#52]
Google Photos allows you to select multiple photos by holding shift and clicking. For some reason Link Clump inhibits this process. You can hold shift, but the clicking isn't registered by Google Photo. Once Link Clump is disabled, the multi-photo selection works fine.

I had Link Clump's optional activation key as shift. As a temporary fix I've changed this to ctrl.

**Comment by benblack86** [comment]
Your suggested change is the only way to fix it.

**Comment by bzle** [comment]
Shouldn't Link Clump only be activated if you start dragging the cursor?

It seems like Google Photo's multi-select clicking and Link Clumps click and drag shouldn't interfere with each other.

**Comment by benblack86** [comment]
No, it is activated by a combination of key and mouse, so the action that Google Photos is expected is the same that linkclump is expecting. It is difficult for the browser to know whether you are trying to select photos or initiating linkclump.

**Comment by bzle** [comment]
Interesting. Ok, thanks for chiming in here so quickly!
