### ISSUE TITLE
Great job and one little suggestion

### ISSUE THREAD

**Issue by Kaorw** [benblack86/linkclump#53]
U make me to have 30 free min by using linkclump.

I was tired clicking lots of links everyday works.

Thanks a lot!

here's little request. 

If linkclump can open links that have no visit history - links that show as grey color not blue - would be perfect.

thanks

**Comment by Hrxn** [comment]
Good idea, but I think it's not actively developed anymore..

**Comment by benblack86** [comment]
Will accept PRs.

**Comment by benblack86** [comment]
Closing since I don't think this is possible?
