### ISSUE TITLE
Not working (June 24 2016)

### ISSUE THREAD

**Issue by zimmhop17** [benblack86/linkclump#55]
I haven't used it in a week because I was on vacation but when I came back it just wasn't working. I wasn't sure if my settings got changed, but I couldn't even find the settings page. So I deleted it and re-downloaded it, but it never asked me for my settings. Something is wrong.

**Comment by benblack86** [comment]
Can you see the extension page? chrome://extensions Can you see Linkclump listed?

**Comment by zimmhop17** [comment]
Yes. It's there and it says that it is enabled.
It still isn't giving me the settings and it still isn't working for me for some reason on my lap top. I just got a new desk top and it works on there. Not sure what's wrong.
