### ISSUE TITLE
[Feature Request] Add support for checkboxes

### ISSUE THREAD

**Issue by arcastro** [benblack86/linkclump#56]
The equivalent extension to this in Firefox is called ["Snap Links"](https://addons.mozilla.org/en-US/firefox/addon/snaplinksplus/)
- When you lasso over checkboxes, it toggles them on or off. 

If possible, I'd like to see this functionality also added to LinkClump

**Comment by benblack86** [comment]
It seems like totally different functionality so I wouldn't be adding it.

**Comment by katelynienaber** [comment]
I like this idea! This is the only thing I would like to use linkclump for P:

**Comment by katelynienaber** [comment]
Especially since snap links is not available in chrome...
