### ISSUE TITLE
[Feature Request] Copy content including links to clipboard

### ISSUE THREAD

**Issue by devincurrie** [benblack86/linkclump#57]
There are times when I'd like to copy the content INCLUDING the links. I don't this option available in LinkClump that will allow me to do this.

**Comment by benblack86** [comment]
I'm not sure what you mean by this. The copy option does include the link.

**Comment by devincurrie** [comment]
Hi Ben,

I'll provide examples so you can better understand what I am talking about. See screenshots at bottom.

As example, we'll attempt to capture text at this webpage: http://www.pcgamer.com/the-e3-2017-conferences-reviewed/

If I copied text (CTRL+C) to clipboard and paste (CTRL+V) into Notepad, I'll lose the links as follow:

> Today I watched the EA, Bethesda, Ubisoft and Microsoft conferences back to back, which is a non-stop bombardment of the senses that veers on torture. And here’s what I thought of each of them, minus the Sony one. It’s been a weirdly low-key E3, with very few on-stage embarrassments, which makes me weirdly nostalgic for the shambolic, teeth-gritting catastrophes of the early 2000s. We did our own conference of course, The PC Gaming Show, but it would be weird to review that, so follow that link to catch up with all the big announcements we had there. 

The links are retained if I copy/paste into MS Word as follow:

> Today I watched the [EA](http://www.pcgamer.com/watch-the-ea-play-e3-press-conference-live/), [Bethesda](http://www.pcgamer.com/watch-bethesdas-e3-press-conference-live/), [Ubisoft](http://www.pcgamer.com/watch-ubisofts-e3-press-conference-live/) and [Microsoft](http://www.pcgamer.com/watch-the-microsoft-e3-press-conference-live/) conferences back to back, which is a non-stop bombardment of the senses that veers on torture. And here’s what I thought of each of them, minus the [Sony](http://www.pcgamer.com/watch-sonys-e3-press-conference-live/) one. It’s been a weirdly low-key E3, with very few on-stage embarrassments, which makes me weirdly nostalgic for the shambolic, teeth-gritting catastrophes of the early 2000s. We did our own conference of course, [The PC Gaming Show](http://www.pcgamer.com/watch-pc-gaming-show-2017-e3-livestream/), but it would be weird to review that, so follow that link to catch up with all the big announcements we had there. 

Using Linkclump, holding down the right mouse button and dragging the bounding box to capture and copy links to clipboard as follow (as seen in the second screenshot):

> EA	http://www.pcgamer.com/watch-the-ea-play-e3-press-conference-live/
> Bethesda	http://www.pcgamer.com/watch-bethesdas-e3-press-conference-live/
> Ubisoft	http://www.pcgamer.com/watch-ubisofts-e3-press-conference-live/
> Microsoft	http://www.pcgamer.com/watch-the-microsoft-e3-press-conference-live/
> Sony	http://www.pcgamer.com/watch-sonys-e3-press-conference-live/
> The PC Gaming Show	http://www.pcgamer.com/watch-pc-gaming-show-2017-e3-livestream/

There are times when I'd like to copy the text INCLUDING the links. I'd like to be able to use Linkclump to capture both the text and links, copy to clipboard, and allow me to easily paste into Notepad to something like this:
> Today I watched the EA (http://www.pcgamer.com/watch-the-ea-play-e3-press-conference-live/), Bethesda (http://www.pcgamer.com/watch-bethesdas-e3-press-conference-live/), Ubisoft (http://www.pcgamer.com/watch-ubisofts-e3-press-conference-live/) and Microsoft (http://www.pcgamer.com/watch-the-microsoft-e3-press-conference-live/) conferences back to back, which is a non-stop bombardment of the senses that veers on torture. And here’s what I thought of each of them, minus the Sony (http://www.pcgamer.com/watch-sonys-e3-press-conference-live/) one. It’s been a weirdly low-key E3, with very few on-stage embarrassments, which makes me weirdly nostalgic for the shambolic, teeth-gritting catastrophes of the early 2000s. We did our own conference of course, The PC Gaming Show (http://www.pcgamer.com/watch-pc-gaming-show-2017-e3-livestream/), but it would be weird to review that, so follow that link to catch up with all the big announcements we had there.

I've been using Linkclump for more than a year now and am still using it. Love this addon. It would be great if we can improve Linkclump further so it can capture both the text and links as well.

![screenshot1](https://user-images.githubusercontent.com/6366445/27115633-d1ed3aa6-5080-11e7-80c2-41c1d8b91a83.jpg)
![screenshot2](https://user-images.githubusercontent.com/6366445/27115632-d1ecf3a2-5080-11e7-8561-399da5b35e53.jpg)

**Comment by Hrxn** [comment]
Not sure if this can be really fixed at all.. When you select text in the browser (with left mouse), it is something entirely different to what the extension does. Things like this can't be accessed from an extension at all, I think..

Also, things like this are usually very dependent on the platform. Which Word are you using, on Windows or Mac OS? I don't know if they behave the same, as they possibly should, but you never know.

If I try Wordpad on Windows, I lose the links and the formatting options, although Wordpad should be able to handle the formatting.

Google Docs on the other hand seems to work. Would probably be a good idea if the browser could simply send out standard RTF or something.

It would probably be easier to use Word or any other word processor that can handle formatting and links etc., save the data as any standard document format and then use something like pandoc to convert to Markdown or something..

**Comment by benblack86** [comment]
The extension can access the text. However, it would be quite a bit of work and not really the purpose of the extension. Adding more functionality makes it less usable and easy to understand.

**Comment by Hrxn** [comment]
As plain text?

**Comment by devincurrie** [comment]
Well I haven't found a solution yet that will allow me to capture both text and links to paste as plain text. Food for thought.

**Comment by benblack86** [comment]
Extensions can access all html elements, so to get the text it would have to find the <p></p> block and get the content.

**Comment by devincurrie** [comment]
To get text, use left mouse button. To get html, use right button.

Is it possible to merge the left functionality into the right button?

**Comment by Hrxn** [comment]
Well, if you have the desired part as HTML, you have at least something to work with.
As I said, convert with pandoc into another format for example, it should work.

**Comment by Hrxn** [comment]
> Extensions can access all html elements, so to get the text it would have to find the
block and get the content.

Yes, but this like using the Dev Tools, doesn't it? Or accessing DOM via Script, etc.
Basically, `Element.innerHTML`

But this is not how selection with the mouse works, I think. You can select an copy multiple paragraphs, blocks. etc. even partially..
