### ISSUE TITLE
crashing

### ISSUE THREAD

**Issue by sengkoleng** [benblack86/linkclump#61]
The app keeps on crashing the whole day. Refreshing, remove-add again didn't work.

**Comment by benblack86** [comment]
It would be useful if you could check to see if there is any logging happening as that is the only way I can debug the problem.

Can you open chrome and from the menu select View -> Developer -> JavaScript Console. Do some web browser and wait for the extension to crash. When it crashes, hopefully there will be some outputted to the console. Thanks.
