### ISSUE TITLE
[feature request] ask each time what action should be performed

### ISSUE THREAD

**Issue by tolik89u** [benblack86/linkclump#62]
In settings there are 4 available actions. 
1. And what if I need to set up several of them, but it's difficult for me to remember which hotkey calls which action? It'd be great, if I could tell your extension to ask me each time, what do I want to do with selected links.
2. Also, sometimes I occasionally unintentionally select many links, and they all are opened in new tabs, but I don't want that, because I've just «misclicked». My browser can even «hang» if there is too much tabs — this is a pity. If there was a setting to ask me what to do each time, then I could cancel opening of these links when I click them unintentionally.

Could you please add such a feature?
![2017-01-29 15_03_08-options](https://cloud.githubusercontent.com/assets/18266085/22403830/231d0a30-e634-11e6-8266-a3533858e873.png)

**Comment by benblack86** [comment]
I don't plan on adding this myself.
