### ISSUE TITLE
Linkclump no longer works in Chrome 60.0.3085.0 (Canary)

### ISSUE THREAD

**Issue by virtenebris** [benblack86/linkclump#64]
It stopped a few days ago, I've tried removing, re-adding, no change. So far it's been working in all versions of Chrome. I use Canary next to the Beta build for the sake of two separate profiles. Could you look into this, please?

**Comment by yys310** [comment]
got the same problem

**Comment by benblack86** [comment]
Looks like right mouse button behavior has changed. Left mouse button still works.

**Comment by benblack86** [comment]
Reported chrome bug: https://bugs.chromium.org/p/chromium/issues/detail?id=732632

**Comment by virtenebris** [comment]
Thank you.

**Comment by benblack86** [comment]
Linkclump 2.7.7 has been published with a fix and should be available within a few hours.

**Comment by virtenebris** [comment]
Awesome, thanks.                                                                                                                                                                            From: notifications@github.comSent: June 13, 2017 8:09 PMTo: linkclump@noreply.github.comReply-to: reply@reply.github.comCc: virtenebris@gmail.com; author@noreply.github.comSubject: Re: [benblack86/linkclump] Linkclump no longer works in Chrome 60.0.3085.0 (Canary) (#64)  Linkclump 2.7.7 has been published with a fix and should be available within a few hours.
