### ISSUE TITLE
Default Browser Functionality Blocked by Linkclump Actions

### ISSUE THREAD

**Issue by PromInc** [benblack86/linkclump#65]
## Issue
Depending on the **Activation** settings, default browser functionality may be blocked from operating as desired.

### Linkclump Action Settings:

> Activate by Left mouse button and "ctrl" key

### Blocked functionality
Selecting multiple non-concurrent options in a multi-select box will not work.

This example can be illustrated at this URL:
http://html.com/attributes/select-multiple/

- Select the first option (American flamingo)
- Press and hold the CTRL key
- Select a second non-concurrent option (Greater flamingo)
  - _The second option will not be selected_

### Linkclump Action Settings:

> Activate by Left mouse button and "shift" key

### Blocked functionality
Selecting a range of concurrent options in a multi-select box will not work.

This example can be illustrated at this URL:
http://html.com/attributes/select-multiple/

- Select the first option (American flamingo)
- Press and hold the SHIFT key
- Select another option further down the list (Greater flamingo)
  - _Only the first item remains selected_

## Work Around
It is possible to work around this issue by using the Linkclump options page to **Blacklist** specific domains that Linkclump will not run and thus the default browser functionality works as desired.  This is not ideal however as this extension is essentially not worth having installed...

## Possible Solution
One possible solution to this issue (untested) is to allow for using multiple modifier keys for an action.  

### Example
Allow for **CTRL + SHIFT + Left Mouse Button** to be an option (currently not available in the dropdown as an option).

**Comment by benblack86** [comment]
Yes, linkclump can block browser functionality depending on activation settings and operating system (linux/max process events differently to windows). Since it very much depends on the website design, I've tried to choose sensible defaults. I haven't seen multiple select drop boxes in the wild apart from tutorials on HTML so I'm not too worried about it.

**Comment by PromInc** [comment]
Thanks for the response @benblack86.  I respect your opinion but am saddened to hear that this won't get consideration.

I am a developer in Magento - one of the largest ecommerce platforms - and they use the multi-selects all over the place.

I feel your defaults were a nice starting point but given that the extension is designed to be customizable I have enjoyed the opportunity to configure it how it fits with my workflow.  Having the option to use multiple modifiers would be a small change to make this extension more universal.

That's my two cents on the issue.  Thank you so much for the great tool!

**Comment by benblack86** [comment]
For your particular case using a different key will solve the problem, i.e. use left mouse button + "a".
