### ISSUE TITLE
LinkClump, right key hold not working

### ISSUE THREAD

**Issue by thusgaard** [benblack86/linkclump#68]
Used to use the right key hold to select multiple links. This no longer seems to work.

What DOES work is to move the selection to the left mouse key and include a keyboard key, like ctrl.

**Comment by benblack86** [comment]
What OS? I'm guessing this is in chrome canary?

**Comment by benblack86** [comment]
Reported chrome bug: https://bugs.chromium.org/p/chromium/issues/detail?id=732632

**Comment by thusgaard** [comment]
Browser: Chrome Version 60.0.3112.24 (Official Build) beta (64-bit)
OS: Windows 10 Pro, 64-bit, Version 1703, OS Build: 15063.296

Further details: When holding the right mouse button, selection doesn't happen. Instead configuring linkclump to use ctrl+left mouse button hold will enable selection of links to open.

In short, I'm not using Canary - just beta.

**Comment by benblack86** [comment]
Linkclump 2.7.7 has been published with a fix and should be available within a few hours.

**Comment by thusgaard** [comment]
This is great. Problem fixed through forcing the extension to update to 2.7.7 and restarting Chrome.

Thanks a bunch. Gotta hurry back to the webstore and update my rating and review!! 🥇
