### ISSUE TITLE
Linkclump changes website you're "visiting" from (referer).

### ISSUE THREAD

**Issue by thecakeisalie25** [benblack86/linkclump#70]
Using linkclump in open tab mode, on a website that checks which website you are visiting from reports a different website than the original, making it impossible to use some websites.

An example would be any of the links from IGG-GAMES.com. 

I'm assuming that this happens because it just opens a new tab with the URL of the link, instead of actually "clicking" the link. If somebody could add in a mode where it actually clicks the link or acts like it does (even with a one second delay would be fine), that would fix the issue. Thanks.

**Comment by thecakeisalie25** [comment]
Alternatively, you could manually change the referer (yes, it's spelled wrong in the http standard) to the current page's URL.

**Comment by benblack86** [comment]
This is the code for opening a link: https://github.com/benblack86/linkclump/blob/master/src/background.js#L31

And as far as I'm aware there is no way to set referer. See https://developer.chrome.com/extensions/tabs#method-create

**Comment by thecakeisalie25** [comment]
This maybe? Also, side question, do you manage the version on the Opera web store? 
![image](https://user-images.githubusercontent.com/9502466/27461596-6901f2be-5780-11e7-973e-6946924b81a3.png)

**Comment by benblack86** [comment]
No, that is just an integer number for internal tab communication. And no I don't look after the opera version.
