### ISSUE TITLE
Linkclump don't work anymore

### ISSUE THREAD

**Issue by galkimera** [benblack86/linkclump#71]
All is in the title, nothing happen with the long right-click, just the web menu. Please help, this extension is too usefull, I need it!!

**Comment by benblack86** [comment]
What OS, what browser version?

**Comment by galkimera** [comment]
Windows 8.1, Chrome Version 59.0.3071.109

**Comment by galkimera** [comment]
Thank you, it work again!!! Thanks to be so reactive!! <3

**Comment by benblack86** [comment]
I didn't do anything, but you are welcome!
