### ISSUE TITLE
Clump-Lines disappear, automatically opens without letting the mouse button go

### ISSUE THREAD

**Issue by mirkomainstream** [benblack86/linkclump#72]
Hey,

in the last 2 weeks i discovered 2 Bugs i never encountered before:
#1 If im going to clump a few links, the "drag-line" somehow disappears sometimes, and causes to not open anything. 

2# Im about to select a few links, it will automatically open them, without me letting the mouse button go, causing in different circumstances extreme performance pressure.

Till this event, this is the best extension ever, but sadly something went wrong here :-/

Any ideas?

Thanks in advance for your reply, best

- Mirko

**Comment by benblack86** [comment]
To be able to help, the issues you are seeing need to be recreatable. Do you have steps to recreate?

**Comment by mirkomainstream** [comment]
Hey, thanks for the quick response.

I don´t know how to recreate, on every Website I visit, the same problems appear - regardless on what i want to clump. :-/

 

 

Best

 

- Mirko

 

Gesendet: Mittwoch, 05. Juli 2017 um 15:46 Uhr
Von: "Benjamin Black" <notifications@github.com>
An: benblack86/linkclump <linkclump@noreply.github.com>
Cc: mirkomainstream <mirkokuenkler@gmx.de>, Author <author@noreply.github.com>
Betreff: Re: [benblack86/linkclump] Clump-Lines disappear, automatically opens without letting the mouse button go (#72)


To be able to help, the issues you are seeing need to be recreatable. Do you have steps to recreate?
