### ISSUE TITLE
Linkclump does not handle line breaks

### ISSUE THREAD

**Issue by mallove** [benblack86/linkclump#73]
If a hyperlink is split across two lines, linkclump only seems to find the start of the link (and not the second part).  For example, in the following screencast for a demonstration, *user* (on the first line) activates the link, but not *agent* (on the following line):

![linkclump doesn t handle line breaks](https://user-images.githubusercontent.com/17302884/28021202-1d30dd40-6555-11e7-96ed-99349066beb7.gif)

**Comment by benblack86** [comment]
Thanks for the gif! This is a known problem, and I don't think it is fixable. The problem is that we know where the link starts and how long it is, but we don't know how it is eventually rendered (and possible split into multiple sections). Any suggestions welcome.
