### ISSUE TITLE
LinkClump activates after switching tab in Chrome

### ISSUE THREAD

**Issue by sekssoglasny** [benblack86/linkclump#74]
even WITHOUT holding Shift key
this happens when I want to highlight certain words using my mouse left click hold normally...

Mac OS El Capitan X
10.11.6 (15G1510)

Chrome 
Version 59.0.3071.115 (Official Build) (64-bit)
Automatic updates are turned on

**Comment by benblack86** [comment]
Not sure I understand. Can you give steps to reproduce, and provide screenshot of your linkclump settings.
