### ISSUE TITLE
cPanel File Manager

### ISSUE THREAD

**Issue by devincurrie** [benblack86/linkclump#77]
Hello,

When I right click on a folder or a file within cPanel's File Manager, it automatically selected other files when I move the mouse up/down to pick out an option from the context menu. This is not normal behaviour. Right clicking on a file/folder makes it behave as if I'm holding down the left button to select other files/folder from the initial selection (anchor).

With Linkclump extension disabled and after refresh of the file manager window, the context menu works normally using the right mouse button. Same goes for the trackpad on my laptop.

**Comment by benblack86** [comment]
Sounds like you need to change the activation keys for linkclump since it is conflicting with the cPanel functionality. What settings do you use?

**Comment by devincurrie** [comment]
I have figured it out by adding the cPanel File Manager's URL to the Linkclump blacklist.
