### ISSUE TITLE
Linkclump in Opera

### ISSUE THREAD

**Issue by HenriVi** [benblack86/linkclump#80]
Hi,

is Linkclump supported in Opera ?

It was working previously, but after recent updates in Opera, it seemed to not operate anymore (no selecting rectangle). This is a handy tool and I do like Opera for it's privacy and lightweight design over other browsers, and I don't know other tool for Opera with similar usage.

-Henri

**Comment by benblack86** [comment]
It's not supported by me. It is a chrome extension.

**Comment by HenriVi** [comment]
Okey, thanks for your response.

-Henri
