### ISSUE TITLE
Exclude visited links using the chrome.history API?

### ISSUE THREAD

**Issue by portablesoft** [benblack86/linkclump#88]
Please provide the following information when creating a bug report:

+ Linkclump version: 2.8.3
+ Operating system: Windows 10 1709 x64
+ Actions you have setup (screen shoot of options page is fine): default settings

About the chrome.history api:

Use the chrome.history API to interact with the browser's record of visited pages. You can add, remove, and query for URLs in the browser's history. 

https://developer.chrome.com/extensions/history

Thanks.

**Comment by benblack86** [comment]
This has already been suggested, but the chrome history api has no way to search. You have to retrieval all and do the search in the extension, which is not performant.
