### ISSUE TITLE
issue with chromebook, wireless mouse 

### ISSUE THREAD

**Issue by ryan021** [benblack86/linkclump#89]
Please provide the following information when creating a bug report:

+ Linkclump version: newest, just got yesterday
+ Operating system: acer chromebook 14 cb3-431-c5fm
+ Actions you have setup (screen shoot of options page is fine):

when i right click and drag with the mouse to use link clump like i normally would on a windows, I just get a regular right click. I can use the  track pad (click with z and drag), but using the wireless mouse it doesn't work.

Please let me know if you know how to fix this as I can't find anything online and really like the extension.

Thanks,
Ryan

**Comment by benblack86** [comment]
When using the wireless mouse, are you sure you are doing a right click?

**Comment by ryan021** [comment]
Hi Ben,

Yes, positive. I appreciate the quick response!

Best,
Ryan

**Comment by ryan021** [comment]
It wouldn't be because I have adguard adblocker right? Not really sure what
else could be going on. Brand new chromebook and wireless mouse and
everything else seems to be working fine.

**Comment by benblack86** [comment]
There should be no difference between your track pad and wireless mouse. What options do you have setup?

**Comment by ryan021** [comment]
Hi Ben,

I think they're the normal ones. I didn't change anything...that I am aware
of

[image: Inline image 1]

Best,
Ryan
