### ISSUE TITLE
Non-functional on new computer

### ISSUE THREAD

**Issue by Alphacaeus** [benblack86/linkclump#90]
Please provide the following information when creating a bug report:
+ Linkclump version:2.8.3
+ Operating system: Windows 10 education version
+ Actions you have setup (screen shoot of options page is fine):
![image](https://user-images.githubusercontent.com/35320282/34807948-726e758e-f659-11e7-8cea-23ee4367f3ff.png)
  Hey! I love your extension for chrome and its derivative browsers, however for some reason I can't use it on this new computer I've put together. I have windows10 edu so perhaps that could be the issue, but I also used ninite toinstall chrome. Overall, i don't think either of these could possible be the suspect of the problem, as I havent had problems with either in the past in respect to Link Clump.

**Comment by benblack86** [comment]
First, wanted to say that Linkclump only runs on chrome. What do you mean when you say it doesn't work? The default setup has changed, so you have to use z key and left mouse button, before it was just using right mouse button.

**Comment by Alphacaeus** [comment]
Hi! So, I reinstalled chrome and that seemed to help the issue. 
Linkclump _can_ run on **Vivaldi** and I believe **Chrome Canary**. And by 'it didn't work' I meant it didn't work. Any configuration of settings lead to no progress.

 Thanks anyway, and I wish you luck on this and your other projects.
