### ISSUE TITLE
Opening links incorrectly 

### ISSUE THREAD

**Issue by ib12345** [benblack86/linkclump#91]
Hello 
I suspect the problem goes deeper that linkclump. 
A lot of people seem to have a problem with chrome where by opening links in new tabs causes them to open incorrectly. As such i had downloaded "command-click fix" extension which seem to fix the problem. 
However linkclump when opening new tabs still causes the links to open incorrectly. 
Is there any way around this ?
Many thanks

**Comment by benblack86** [comment]
I don't know what you mean by "open incorrectly".

**Comment by ib12345** [comment]
Hello
A good example of this is booking.com
I am running sierra on mac book Pro.
If I want to open all hotels on a page of booking.com say hotels in Lazio. Booking.com lists these 15 at a time which means clicking each link.
For some reason however, and only on chrome, clicking the command and click function on the link for a specific hotel, opens up a new page, however not the direct link to the hotel page like it would in other browsers.
Any help much appreciated


Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by benblack86** [comment]
This doesn't seem related to linkclump. Using command+click opens a new tab with the hotel listing. I can use linkclump to open multiple links at once, which also works.
