### ISSUE TITLE
Stopped Working

### ISSUE THREAD

**Issue by M-aple** [benblack86/linkclump#93]
Please provide the following information when creating a bug report: So the only add-on I've ever used is Linkclump and today I was in the middle of surfing around and playing on my games when the linkclump tutorial randomly popped up and without thinking anything of it I just clicked out of it, but immediately after realized that when right clicking and dragging it no longer works. I tried closing chrome and reopening and even restarting the laptop but it still doesn't work.

Edit: I now see that it only does it if I press z and left click, is there a way for me to set it back to the original just right click? That's much easier for me.

+ Linkclump version: 2.8.3
+ Operating system: Windows 7 laptop
+ Actions you have setup (screen shoot of options page is fine): not sure what you mean by this?

**Comment by benblack86** [comment]
You should look at the options page. Click on linkclump -> options.

**Comment by M-aple** [comment]
Thanks. Is there any way you could point out where the options are? Or am I not supposed to go to linkclump through the chrome web store?

**Comment by benblack86** [comment]
Go to the extensions page, goto chrome://extensions or click on the three dots on the right hand side -> More tools -> Extensions
