### ISSUE TITLE
Correctly marks, cannot open / lags indefinitely

### ISSUE THREAD

**Issue by stdedos** [benblack86/linkclump#94]
+ Linkclump version: 2.8.3
+ Operating system: Windows 10 1709 (16229.19)
+ Actions you have setup (screen shoot of options page is fine):
![image](https://user-images.githubusercontent.com/133706/35825491-af3128bc-0abe-11e8-9a02-c99aabe95ede.png)

Marks correctly 13 images, extension lags indefinitely until 're-called' (where you loose your progress)
http://cpuboss.com/blog/overly-suave-it-guy-has-all-the-sleezy-tech-pickup-lines-that-will-never-ever-work/

**Comment by stdedos** [comment]
_Any_ comment on why/how you closed this would be a common courtesy ...

**Comment by benblack86** [comment]
Issue is old, link doesn't work.
