### ISSUE TITLE
Auto-create GitHub Issue Ticket necessary info

### ISSUE THREAD

**Issue by stdedos** [benblack86/linkclump#95]
Self-explanatory: Direct POST with the necessary information, or a Copy/Paste box

_Following probably are not necessary, but for the sake of completeness:_

+ Linkclump version: 2.8.3
+ Operating system: Windows 10 1709 (16229.19)
+ Actions you have setup (screen shoot of options page is fine):
![image](https://user-images.githubusercontent.com/133706/35825491-af3128bc-0abe-11e8-9a02-c99aabe95ede.png)

**Comment by stdedos** [comment]
_Any_ comment on why/how you closed this would be a common courtesy ...

**Comment by benblack86** [comment]
Not going to do (PR welcome!)
