### ISSUE TITLE
Firefox

### ISSUE THREAD

**Issue by MoneyAllDay** [benblack86/linkclump#96]
Can you possibly add support for Firefox? The alternatives are not as good as LinkClump.

Sorry for asking this here but i don't know where else to post it, thanks.

**Comment by andreicristianpetcu** [comment]
Please add a Firefox extension. Most Chrome extensions can be converted really easy https://vimeo.com/241435808 the APIs are the same https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Browser_support_for_JavaScript_APIs

**Comment by MoneyAllDay** [comment]
Wow it's been a year now... My hope is still alive.

**Comment by benblack86** [comment]
I wouldn't hope too much. I don't intend to work on this project, but I'm happy to accept PRs for any necessary changes.

**Comment by Coldblackice** [comment]
Anyone that could add Firefox support would truly be the hero that Gotham needs.
