### ISSUE TITLE
Linkclump operation erratic

### ISSUE THREAD

**Issue by kemmatech** [benblack86/linkclump#97]
+ Linkclump version: 2.8.3
+ Operating system: Windows 10
+ Actions you have setup (screen shoot of options page is fine): 

Opened as New Tabs
Activate by Right mouse button
smart select: on
block repeat links in selection: true

I use Linkclump extensively (over a hundred times a day) but it's frustrating me because it frequently doesn't work. Sometimes it works find, and then other times I try to drag over a list of links and they just don't highlight. It's driving me crazy. I've noticed a correlation between the times that it doesn't work and when I try to bring up the options page, it just hangs. As soon as the options page comes up, I can go back to the browser tab I was working on, refresh the page, and then I am able to highlight links. My guess is that upon each page load, a request is made to some server to load a piece of javascript or something to allow for highlighting of the links, but that page that hosts the code doesn't always respond. Maybe I have no idea what I'm talking about, but I know that the extension only works sporadically and I'm at the point where I'm frustrated enough to uninstall it. Hoping to avoid that, so wanted to see if anyone had any suggestions. Thanks.

**Comment by benblack86** [comment]
There are no requests sent to a server/service. Everything is calculated in the browser. Maybe there is a memory leak? Seems unlikely since the extension is reloaded on each page load. Without being able to reproduce, it will be very difficult to debug.

**Comment by kemmatech** [comment]
It's very strange then because often I will go to the Linkclump options page and it will just hang there for anywhere from 30 seconds to a few minutes and then all of a sudden appear. I guess I need to look further at a local environment issues if it's not making any requests to some external IP. Thanks for the quick response though.
