### ISSUE TITLE
Future Support for Safari on MacOS?

### ISSUE THREAD

**Issue by haofeiyan** [benblack86/linkclump#99]
Please provide the following information when creating a bug report:

+ Linkclump version:
+ Operating system: MacOS 10.13.3
+ Actions you have setup (screen shoot of options page is fine):

Hello,
I really like this chrome extension. However, it is a nightmare to use it on Chrome in MacOS when I want to open 50 tabs in one time...

**Comment by mefengl** [comment]
@haofeiyan Hey, I reimplemented it in userscript, so that it can be used in Safari by Tampermonkey extension, hope it will help.

https://greasyfork.org/scripts/471560
